package main

// Code generated by gen_test.py

import (
	"testing"
	. "transcendence/conf"
)

func TestConfig(t *testing.T) {
	t.Log(I("BUF_QUEUE"))
	t.Log(S("CLUSTER_LOG_PATH"))
	t.Log(S("CLUSTER_NODE_ADDR"))
	t.Log(S("CLUSTER_NODE_CONNECT2"))
	t.Log(S("CLUSTER_NODE_NAME"))
	t.Log(I("CLUSTER_NODE_PORT"))
	t.Log(S("CTX_REG"))
	t.Log(S("HIVE_LISTEN_ADDR"))
	t.Log(S("HOST_SERVICE"))
	t.Log(S("HTTP_LISTEN_ADDR"))
	t.Log(TS("HTTP_LISTEN_URLS"))
	t.Log(I("HTTP_TIME_OUT"))
	t.Log(I("MAX_LEN_HEAD"))
	t.Log(I("POST_TIME_OUT"))
	t.Log(S("RAFT_ADDR"))
	t.Log(I("RAFT_DB_SIZE"))
	t.Log(S("REDIS_LEADER_TIMER_KEY"))
	t.Log(I("SERVICE_APPID"))
	t.Log(I("SERVICE_LISTEN_PORT"))
	t.Log(S("SERVICE_REGKEY"))
	t.Log(S("URL_SERVICE_BROADCAST"))
	t.Log(S("URL_SERVICE_MULTICAST"))
	t.Log(S("URL_SERVICE_REG"))
	t.Log(S("URL_SERVICE_UNICAST"))
	t.Log(I("V1"))
	t.Log(I("V2"))
}
