
import sys; sys.path.extend(["../conf/", "./conf/"])
import config


head = """package main

// Code generated by gen_test.py

import (
	"testing"
	. "transcendence/conf"
)

func TestConfig(t *testing.T) {
"""

tail = """}
"""

f = file("./transcendence_test.go", "w")
f.write(head)

for attr in dir(config):
    if attr.startswith("__"):
        continue

    ty = ""
    if type(getattr(config, attr)) == type(""):
        ty = "S"
    elif type(getattr(config, attr)) == type(0):
        ty = "I"
    else:
        ty = "TS"

    f.write('\tt.Log(%s("%s"))\n' % (ty, attr))

f.write(tail)
f.close()
